using System.Text;

namespace Convex.Client.Extensions.Clerk;

/// <summary>
/// Generates Convex auth.config.ts templates for Clerk OAuth integration.
/// </summary>
public static class ClerkAuthConfigGenerator
{
    /// <summary>
    /// Generates a complete auth.config.ts file for Convex with Clerk custom JWT provider.
    /// </summary>
    /// <param name="clerkDomain">Clerk domain (e.g., "tough-foal-55.clerk.accounts.dev")</param>
    /// <param name="oauthClientId">OAuth Client ID from Clerk (matches JWT 'aud' claim)</param>
    /// <returns>Complete TypeScript auth.config.ts file content</returns>
    public static string GenerateAuthConfig(string clerkDomain, string oauthClientId)
    {
        if (string.IsNullOrWhiteSpace(clerkDomain))
            throw new ArgumentException("Clerk domain cannot be empty", nameof(clerkDomain));
        if (string.IsNullOrWhiteSpace(oauthClientId))
            throw new ArgumentException("OAuth Client ID cannot be empty", nameof(oauthClientId));

        // Remove https:// if present
        clerkDomain = clerkDomain.Replace("https://", "").Replace("http://", "");

        return $$"""
        /**
         * Convex Authentication Configuration
         *
         * For OAuth desktop applications, we configure Convex to validate OAuth id_tokens
         * by treating Clerk as a custom JWT issuer with OIDC discovery.
         *
         * Generated by Convex.Client.Extensions.Clerk
         * Convex will automatically discover the JWKS endpoint from:
         * https://{{clerkDomain}}/.well-known/openid-configuration
         */

        import { AuthConfig } from "convex/server";

        export default {
          providers: [
            {
              // Custom JWT provider configuration
              type: "customJwt" as const,

              // OAuth Client ID that must match the "aud" claim in id_token
              applicationID: "{{oauthClientId}}",

              // JWT issuer URL (must match "iss" claim in id_token)
              issuer: "https://{{clerkDomain}}",

              // JWKS endpoint for token validation
              jwks: "https://{{clerkDomain}}/.well-known/jwks.json",

              // Algorithm used for signing (Clerk uses RS256)
              algorithm: "RS256" as const,
            },
          ],
        } satisfies AuthConfig;

        """;
    }

    /// <summary>
    /// Extracts Clerk domain and client ID from ClerkOptions and generates auth.config.ts.
    /// </summary>
    /// <param name="options">Clerk options containing PublishableKey and OAuthClientId</param>
    /// <returns>Complete TypeScript auth.config.ts file content</returns>
    public static string GenerateAuthConfig(ClerkOptions options)
    {
        if (options == null)
            throw new ArgumentNullException(nameof(options));
        if (string.IsNullOrWhiteSpace(options.PublishableKey))
            throw new ArgumentException("PublishableKey is required", nameof(options));
        if (string.IsNullOrWhiteSpace(options.OAuthClientId))
            throw new ArgumentException("OAuthClientId is required", nameof(options));

        var domain = ExtractClerkDomain(options.PublishableKey);
        var clientId = options.OAuthClientId;

        return GenerateAuthConfig(domain, clientId);
    }

    /// <summary>
    /// Extracts Clerk domain from publishable key.
    /// Publishable key format: pk_test_{base64-encoded-domain}_{random}
    /// </summary>
    private static string ExtractClerkDomain(string publishableKey)
    {
        if (string.IsNullOrWhiteSpace(publishableKey))
            throw new ArgumentException("Publishable key cannot be empty", nameof(publishableKey));

        // Publishable key format: pk_test_base64domain_randomsuffix or pk_live_base64domain_randomsuffix
        var parts = publishableKey.Split('_');
        if (parts.Length < 3)
            throw new ArgumentException("Invalid publishable key format", nameof(publishableKey));

        try
        {
            // Decode base64 domain from middle part
            var base64Domain = parts[2];
            var domainBytes = Convert.FromBase64String(base64Domain);
            var domain = Encoding.UTF8.GetString(domainBytes);
            return domain;
        }
        catch (Exception ex)
        {
            throw new ArgumentException($"Failed to extract Clerk domain from publishable key: {ex.Message}", nameof(publishableKey), ex);
        }
    }

    /// <summary>
    /// Generates setup instructions for integrating Clerk with Convex.
    /// </summary>
    public static string GenerateSetupInstructions(string clerkDomain, string oauthClientId)
    {
        return $$"""
        # Clerk + Convex OAuth Setup Instructions

        ## 1. Create auth.config.ts in your Convex backend

        Create `backend/convex/auth.config.ts` with the following content:

        ```typescript
        {{GenerateAuthConfig(clerkDomain, oauthClientId)}}
        ```

        ## 2. Deploy your Convex backend

        ```bash
        cd backend
        npx convex dev --once
        ```

        ## 3. Verify configuration

        - Clerk domain: https://{{clerkDomain}}
        - OAuth Client ID: {{oauthClientId}}
        - JWKS URL: https://{{clerkDomain}}/.well-known/jwks.json

        ## Common Issues

        ### Authentication fails with "Authentication required"
        - Verify `applicationID` matches your OAuth Client ID exactly
        - Verify `issuer` matches the `iss` claim in your JWT token
        - Check that auth.config.ts has been deployed (run `npx convex dev --once`)

        ### "InvalidAuthConfig" error
        - Ensure all required fields are present: type, applicationID, issuer, jwks, algorithm
        - Verify TypeScript syntax is correct (`as const` on type and algorithm)
        - Import `AuthConfig` from "convex/server"

        ### WebSocket subscription failures
        - Authentication must complete before subscriptions are created
        - Check browser/app console for AuthError messages
        - Verify JWT token is not expired

        ## Documentation

        - Convex Custom JWT: https://docs.convex.dev/auth/advanced/custom-jwt
        - Clerk OAuth: https://clerk.com/docs/authentication/social-connections/oauth
        """;
    }
}
