/**
 * Convex database schema definition
 * 
 * This file was automatically generated by BackendGenerator.
 * Do not modify this file directly.
 */

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  /**
   * Represents a todo item in the application.
   */
  todos: defineTable({
    title: v.string(),
    description: v.string(),
    isCompleted: v.boolean(),
    priority: v.union(v.literal("Low"), v.literal("Normal"), v.literal("High"), v.literal("Urgent")),
    createdAt: v.number(),
    updatedAt: v.number(),
    dueDate: v.optional(v.number()),
    tags: v.array(v.string()),
    category: v.string(),
})
    .index("createdAt", ["createdAt"])
    .index("updatedAt", ["updatedAt"])
    .searchIndex("title", {
      searchField: "title"
    })
    .searchIndex("description", {
      searchField: "description"
    })
  ,
});
