/**
 * TypeScript type definitions for database models
 * 
 * This file was automatically generated by BackendGenerator.
 * Do not modify this file directly.
 */

/**
 * Priority levels for todo items.
 */
export type TodoPriority =
  "Low" |
  "Normal" |
  "High" |
  "Urgent";

/**
 * Type of optimistic operation.
 */
export type OperationType =
  "Create" |
  "Update" |
  "Delete";

/**
 * Status of an optimistic operation.
 */
export type OperationStatus =
  "Pending" |
  "Committed" |
  "Failed";

/**
 * Interaction logic for App.xaml
 */
export interface App {
}

/**
 * Converter to convert TodoPriority enum to appropriate brush colors.
 */
export interface PriorityToBrushConverter {
}

/**
 * Converter to check if a todo ID is an optimistic ID.
 */
export interface OptimisticIdConverter {
}

/**
 * Defines Convex database functions for todo management that will be generated
 * into strongly-typed extension methods.
 * These correspond to actual functions deployed to a Convex backend.
 */
export interface ConvexFunctions {
}

export interface MainWindow {
}

/**
 * Represents a todo item in the application.
 */
export interface Todo {
  id: string;
  title: string;
  description: string;
  isCompleted: boolean;
  priority: TodoPriority;
  createdAt: number;
  updatedAt: number;
  dueDate?: number;
  tags: string[];
  category: string;
}

/**
 * Statistics for the todo dashboard.
 */
export interface TodoStats {
  totalTodos: number;
  completedTodos: number;
  pendingTodos: number;
  overdueTodos: number;
  todosByPriority: any;
  todosByCategory: any;
  lastUpdated: number;
}

/**
 * Todos grouped by priority for dashboard display.
 */
export interface TodosByPriority {
  priority: TodoPriority;
  count: number;
}

/**
 * Todos grouped by category for dashboard display.
 */
export interface TodosByCategory {
  category: string;
  count: number;
}

export interface CreateTodo {
  title: string;
  description: string;
  priority: TodoPriority;
  dueDate?: number;
  tags?: string[];
  category: string;
}

export interface UpdateTodo {
  id: string;
  title?: string;
  description?: string;
  isCompleted?: boolean;
  priority?: TodoPriority;
  dueDate?: number;
  tags?: string[];
  category?: string;
}

export interface ToggleTodoCompletion {
  id: string;
  isCompleted: boolean;
}

export interface SearchTodos {
  query?: string;
  isCompleted?: boolean;
  priority?: TodoPriority;
  category?: string;
}

export interface DeleteTodo {
  id: string;
}

/**
 * Helper methods for working with Unix timestamps from Convex.
 */
export interface ConvexHelpers {
}

/**
 * Represents a pending optimistic operation.
 */
export interface PendingOperation {
  type: OperationType;
  optimisticId: string;
  realId?: string;
  status: OperationStatus;
  data?: any;
  error?: string;
  createdAt: number;
  completedAt?: number;
}

/**
 * Represents an optimistic todo with tracking information.
 */
export interface OptimisticTodo {
  todo: any;
  optimisticId: string;
  isPending: boolean;
}

/**
 * Manages optimistic updates for todo operations.
 * Provides immediate UI feedback while waiting for server responses.
 */
export interface OptimisticUpdatesManager {
  pendingOperations: any;
}

