#nullable enable

using System.Collections.Generic;
using Convex.SourceGenerator.Core.Models;

namespace Convex.SourceGenerator.Modules;

/// <summary>
/// Generates DI registration extensions for Convex generated services.
/// </summary>
public class DIModule : IGenerationModule
{
    /// <summary>
    /// Gets the name.
    /// </summary>
    public string Name => "DependencyInjection";

    /// <summary>
    /// Determines whether the module is enabled for the specified generator options.
    /// </summary>
    public bool IsEnabled(GeneratorOptions options) => options.GenerateDI;

    /// <summary>
    /// Generates source files for this module.
    /// </summary>
    public IEnumerable<GeneratedFile> Generate(
        IReadOnlyList<TableDefinition> tables,
        IReadOnlyList<FunctionDefinition> functions,
        GeneratorOptions options)
    {
        // Only generate if services are also being generated
        if (!options.GenerateServices || functions.Count == 0)
        {
            yield break;
        }

        var sb = new Core.Utilities.SourceBuilder();

        sb.EmitFileHeader("This file is automatically generated from your Convex backend.");
        sb.EmitUsings("Microsoft.Extensions.DependencyInjection");
        sb.OpenNamespace(options.Namespace);

        sb.EmitSummary("Extension methods for registering Convex generated services.");
        sb.OpenClass("public static", "ConvexGeneratedExtensions");

        sb.EmitSummary("Registers the generated Convex function services.");
        sb.AppendLine("public static IServiceCollection AddConvexGeneratedServices(this IServiceCollection services)");
        sb.AppendLine("{");
        sb.Indent();
        sb.AppendLine($"services.AddScoped<{options.ServicesNamespace}.IConvexFunctionsService, {options.ServicesNamespace}.ConvexFunctionsService>();");
        sb.AppendLine("return services;");
        sb.Outdent();
        sb.AppendLine("}");

        sb.CloseClass();
        sb.CloseNamespace();

        yield return new GeneratedFile
        {
            FileName = "ConvexDI.g.cs",
            Content = sb.ToString()
        };
    }
}
