#nullable enable

using System.Text;

namespace Convex.SourceGenerator.Core.Utilities;

/// <summary>
/// A StringBuilder wrapper with helpers for code generation.
/// </summary>
public class SourceBuilder
{
    private readonly StringBuilder _sb = new();
    private int _indentLevel;
    private readonly string _indentString;

    public SourceBuilder(string indentString = "    ")
    {
        _indentString = indentString;
    }

    /// <summary>
    /// Increases the indentation level.
    /// </summary>
    public void Indent() => _indentLevel++;

    /// <summary>
    /// Decreases the indentation level.
    /// </summary>
    public void Outdent()
    {
        if (_indentLevel > 0)
        {
            _indentLevel--;
        }
    }

    /// <summary>
    /// Appends a line with the current indentation.
    /// </summary>
    public void AppendLine(string line)
    {
        for (var i = 0; i < _indentLevel; i++)
        {
            _sb.Append(_indentString);
        }
        _sb.AppendLine(line);
    }

    /// <summary>
    /// Appends an empty line.
    /// </summary>
    public void AppendLine()
    {
        _sb.AppendLine();
    }

    /// <summary>
    /// Appends text without indentation or newline.
    /// </summary>
    public void Append(string text)
    {
        _sb.Append(text);
    }

    /// <summary>
    /// Emits the standard auto-generated file header.
    /// </summary>
    public void EmitFileHeader(string description = "This file is automatically generated.")
    {
        AppendLine("// <auto-generated>");
        AppendLine($"// {description}");
        AppendLine("// Do not modify this file directly - changes will be overwritten.");
        AppendLine("// </auto-generated>");
        AppendLine();
        AppendLine("#nullable enable");
        AppendLine();
    }

    /// <summary>
    /// Emits standard using statements.
    /// </summary>
    public void EmitUsings(params string[] namespaces)
    {
        foreach (var ns in namespaces)
        {
            AppendLine($"using {ns};");
        }
        AppendLine();
    }

    /// <summary>
    /// Opens a namespace block.
    /// </summary>
    public void OpenNamespace(string namespaceName)
    {
        AppendLine($"namespace {namespaceName}");
        AppendLine("{");
        Indent();
    }

    /// <summary>
    /// Closes a namespace block.
    /// </summary>
    public void CloseNamespace()
    {
        Outdent();
        AppendLine("}");
    }

    /// <summary>
    /// Opens a class block.
    /// </summary>
    public void OpenClass(string modifiers, string className, string? baseType = null, bool partial = false)
    {
        var partialKeyword = partial ? "partial " : "";
        var declaration = baseType != null
            ? $"{modifiers} {partialKeyword}class {className} : {baseType}"
            : $"{modifiers} {partialKeyword}class {className}";
        AppendLine(declaration);
        AppendLine("{");
        Indent();
    }

    /// <summary>
    /// Closes a class block.
    /// </summary>
    public void CloseClass()
    {
        Outdent();
        AppendLine("}");
    }

    /// <summary>
    /// Opens an interface block.
    /// </summary>
    public void OpenInterface(string modifiers, string interfaceName)
    {
        AppendLine($"{modifiers} interface {interfaceName}");
        AppendLine("{");
        Indent();
    }

    /// <summary>
    /// Closes an interface block.
    /// </summary>
    public void CloseInterface()
    {
        Outdent();
        AppendLine("}");
    }

    /// <summary>
    /// Emits an XML documentation summary.
    /// </summary>
    public void EmitSummary(string summary)
    {
        AppendLine("/// <summary>");
        AppendLine($"/// {summary}");
        AppendLine("/// </summary>");
    }

    /// <summary>
    /// Returns the generated source code.
    /// </summary>
    public override string ToString() => _sb.ToString();
}
